# 데이터 분석
- 인공지능(AI)
    - 머신러닝(ML)
    - 딥러닝(DL)

----------
- 머신러닝_데이터 분석
    - 지도학습 : 데이터에 정답이 포함된 경우
        - 분류분석, 회귀분석 등
    - 비지도학습 : 데이터에 정답이 없는 경우
        - 군집분석
-------
- 딥러닝_데이터 분석
    - 자연어 분석(NLP)
        - 언어 분석 -> 금융권 신용평가, 연체여부 확인, 금융사기 등 
        - 긍정적 / 부정적 여부 확인
    - 이미지 분석
        - 얼굴인증(얼굴 이미지 = 서버의 얼굴 이미지와 동일 여부 확인), 생체인증
        - 퀀트 투자 : 주가와 같은 시계열 데이터의 흐름을 이미지로 인식하여 패턴 파악 및 자동화

# Numpy
- https://numpy.org/numpy-tutorials/
- numpy : Nemerical Python 과학적, 산업적 연상을 위한 패키지
- 다차원 배열, 행렬 연산에 주로 사용
- numpy는 python의 .list와 비슷한 자료형
- 순서가 있는 자료형
- 파이썬의 list와의 차이는 자료형이 1가지만 들어간다


## 차원
- 0차원 = 점, 스칼라(a = 10)
- 1차원 = 선 ----- 벡터, 배열, list, tuple
    - 벡터는 방향을 가진 데이터
    - [1,2,3,4]
- 2차원 = 면, 가로/세로, DB 테이블, DataFrame, matrix
- 3차원 = 입체, 가로(x)/세로(y)/깊이(z), 정육면체
- 4차원 = 3차원 요소가 2개 이상
- 5차원 = 4차원 요소가 2개 이상

------------

- Excel : 기본적으로 2차원(가로/세로)
    - 하나의 셀 = 스칼라
    - 행 벡터(가로), 열 벡터(세로)

In [1]:
import numpy as np

# 1차원 데이터
a = np.array([1,2,3,4,5])
print(a)

# 스칼라
s = 10
print(s)

[1 2 3 4 5]
10


In [9]:
# 1차원 데이터
a = np.array([1,2,3,4,5])
print(a)

In [10]:
# 스칼라
s = 10
print(s)

- 차원을 출력하는 메서드 : .ndim
- 차원의 형태를 출력하는 메서드 : .shape

In [11]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [99]:
# 방향이 없는 벡터
a.shape

(3, 5)

In [100]:
# 차원을 출력하는 메서드 : .ndim
# 차원의 형태를 출력하는 메서드 : .shape

# ndarray는 벡터이므로 1차원
print(a.ndim)

# 방향이 없는 벡터
print(a.shape)

2
(3, 5)


In [104]:
# 새로 방향을 가진 1차원 데이터
a2 = np.array([[1],[2],[3],[4],[5]])
print(a2)


[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)


In [102]:
# 1차원 데이터의 차원과 차원 형태 출력
print(a2.ndim)
print(a2.shape)

2
(5, 1)


In [106]:
# 행벡터
a3 = np.array([[1,2,3,4,5]])
print(a3)

# 2차원 데이터의 차원과 차원 형태 출력
print(a3.ndim)
print(a3.shape)

[[1 2 3 4 5]]
2
(1, 5)


In [37]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [18]:
print(c.ndim)
print(c.shape) # (행, 열) : 2개(2차원)

2
(2, 5)


In [49]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
             [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])

In [50]:
print(d.ndim)
print(d.shape) # ((행/열)2차원 데이터의 수, 행, 열) : 3개(3차원)

3
(4, 2, 5)


In [35]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])

In [29]:
print(e.ndim)
print(e.shape) # (3차원 데이터의 수,(행/열)2차원 데이터의 수, 행, 열) : 4개(4차원)

4
(2, 2, 2, 5)


In [34]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])

In [51]:
print(f.ndim)
print(f.shape) # (4차원 데이터의 수, 3차원 데이터의 수,(행/열)2차원 데이터의 수, 행, 열) : 5개(5차원)

5
(2, 2, 2, 2, 5)


In [59]:
f[0][0][0][0]

array([1, 2, 3, 4, 5])

# Numpy 사용 이유
- 행렬 연산이 쉽고 빠르기 때문

In [65]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)
print(scalar + 10)

15
25


In [67]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]

# 리스트의 요소에 10을 곱한 후 다시 리스트로 만드세요

result = []
for num in b1:
    result.append(num*10)
print(result)

[10, 20, 30, 40, 50]


In [69]:
result2 = [num*10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [77]:
# 2차원 데이터 계산 *10
second = np.array([[1,2,3], [1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [102]:
result = []
for num in second:
#     print(num)
    mid_result = []
    for number in num:
        mid_result.append(number * 10)
    result.append(mid_result)
print(result)


[[np.int64(10), np.int64(20), np.int64(30)], [np.int64(10), np.int64(20), np.int64(30)]]


In [103]:
result = np.array(result)
print(result.ndim)
print(result.shape)

2
(2, 3)


In [80]:
# 3차원 데이터의 요소에 10 곱셈
third = np.array([[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]])
print(third, third.ndim, third.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3 (2, 2, 3)


In [104]:
result = []

for num1 in third:
#     print(num1)
    num1_result = []
    for num2 in num1:
#         print(num2)
        num2_result = []
        for num3 in num2:
            num2_result.append(num3 * 10)
        num1_result.append(num2_result)
    result.append(num1_result)
print(result)


[[[np.int64(10), np.int64(20), np.int64(30)], [np.int64(10), np.int64(20), np.int64(30)]], [[np.int64(10), np.int64(20), np.int64(30)], [np.int64(10), np.int64(20), np.int64(30)]]]


In [105]:
result = np.array(result)
print(result.ndim)
print(result.shape)

3
(2, 2, 3)


In [111]:
# 4차원 데이터 요소에 10 곱셈
forth = np.array([[[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]],
                 [[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]]])
print(forth.ndim, forth.shape)

4 (2, 2, 2, 3)


In [108]:
forth * 10

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [110]:
# 5차원 데이터 요소에 10 곱셈
fifth = np.array([[[[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]],
                 [[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]]],
                 [[[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]],
                 [[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]]]])
print(fifth.ndim, fifth.shape)

5 (2, 2, 2, 2, 3)


In [113]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# Numpy에서 자주 사용하는 메서드
- .ndim : 몇 차원인지 확인
- .shape : 몇 차원, 몇행, 몇열로 되어 있는지 구조 확인
- .size : 배열 안에 있는 요소의 총 개수가 몇 개인지 확인
- .dtype : 데이터 타입이 무엇인지 확인

In [114]:
print(fifth.ndim)
print(fifth.shape)
print(fifth.size)
print(fifth.dtype)

5
(2, 2, 2, 2, 3)
48
int64


In [119]:
# fifth / 2


# ndarray 생성
- numpy의 기본 자료형 ndarray
- np.array(리스트/튜플)
- 자료형은 반드시 1가지만 넣기


In [121]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [122]:
print(*[1,2,3,4,5])

1 2 3 4 5


In [123]:
e = np.array((1,2,3,4,5))
e

array([1, 2, 3, 4, 5])

In [131]:
e = np.array((1,2,3.14,4,5))
e.dtype

dtype('float64')

In [127]:
e3 = np.array((True, 1,2,3.14, '4',5))
print(e3)
e3.dtype

['True' '1' '2' '3.14' '4' '5']


dtype('<U32')

- np.arange(시작, 끝, step)


In [134]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [135]:
a3 = np.arange(1,101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [137]:
# .reshape(행, 열) : 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)

a4 = a3.reshape(20,5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [141]:
a5 = a3.reshape(5,4,5)
print(a5.ndim)
print(a5.shape)

3
(5, 4, 5)


In [144]:
a6 = a3.reshape(4, 25)
print(a6.ndim)
print(a6.shape)
a6

2
(4, 25)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [145]:
# flatten() : 다차원 배열을 1차원으로 펼쳐줌
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [150]:
a72 = a7.flatten()
print(a72.ndim)
print(a72.shape)

1
(24,)


In [153]:
# np.flip() : 행렬의 순서 뒤집는 경우
a73 = a72.reshape(3,2,2,2)
np.flip(a73)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [155]:
a73[-1]

array([[[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [23]:
# np.linspace(시작, 끝, 구간 수) : 정해진 숫자 범위 안에서 균등한 구간을 나누는 경우
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [163]:
np.linspace(0,1, 13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

In [14]:
# 정렬, .sort(), sorted()
f =np.array([5,7,11,1,3,2,54,0,0.5,68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

In [15]:
f.sort() # 저장하지 않아도 자동으로 저장되메
f

array([ 0. ,  0.5,  1. ,  2. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [16]:
# 저장하고 싶지 않다면 sorted 활용
sorted(f)

[np.float64(0.0),
 np.float64(0.5),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(7.0),
 np.float64(11.0),
 np.float64(54.0),
 np.float64(68.0)]

In [17]:
sorted(f, reverse=True)

[np.float64(68.0),
 np.float64(54.0),
 np.float64(11.0),
 np.float64(7.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(0.5),
 np.float64(0.0)]

In [18]:
f = f.reshape(2,5)
f.sort()
f

array([[ 0. ,  0.5,  1. ,  2. ,  3. ],
       [ 5. ,  7. , 11. , 54. , 68. ]])

In [19]:
arr = np.array([[[5, 2, 8], [1, 6, 7]],[[4, 9, 3], [0, 2, 1]]])

In [22]:
# axis=0 2차원 배열
# np.sort() 함수의 axis 기본값은 -1
print(arr)
np.sort(arr, axis=0)

[[[5 2 8]
  [1 6 7]]

 [[4 9 3]
  [0 2 1]]]


array([[[4, 2, 3],
        [0, 2, 1]],

       [[5, 9, 8],
        [1, 6, 7]]])

In [21]:
# argsort() : 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5,0.5, -7, 42,10,0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [181]:
# 2,5,1,0,4,3
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [184]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

- np.where(조건, 참, 거짓) 3항 연산


In [24]:
num = np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.where(num % 2 == 0, '짝수', '홀수')

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

In [27]:
result = []
for i in num:
    if i % 2 == 0:
        result.append('짝수')
    else:
        result.append('홀수')
print(result)

['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수']


# np.concatenate() : 배열 합치기

In [33]:
# 2차원 배열 할당
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(a, a.shape, a.ndim)
print(b, b.shape, b.ndim)

[[1 2]
 [3 4]] (2, 2) 2
[[5 6]
 [7 8]] (2, 2) 2


- np.concatenate((a,b))
- 합치는 기본 방향
    - axis=0 : 행이 들어나서 아래로 붙음
    - axis=1은 열이 늘어나서 옆(오른쪽)으로 붙음


In [35]:
# 2개의 2차원 배열을 합침(배열은 튜플 형식으로 넣음)
axis0 = np.concatenate((a,b))
print(axis0)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
axis1 = np.concatenate((a,b), axis=1)
print(axis1)

[[1 2 5 6]
 [3 4 7 8]]


# 합치는 방향의 모양이 일치하지 않으면 합치지 X

In [37]:
# 1차원 배열 할당
c = np.array([5,6])
print(c, c.shape, c.ndim)

[5 6] (2,) 1


In [47]:
# 차원이 맞지 않다면 합쳐지지 않음(오류 발생)
# np.concatenate((a,c))

In [66]:
d = np.array([[7,8,9]])
print(d)

[[7 8 9]]


In [67]:
print(a)

[[1 2]
 [3 4]]


In [68]:
# a는 2행 2열, d는 1행 3열이므로 맞지 않아 합쳐지지 않음(오류 발생)
# np.concatenate((a,d), axis=1)

In [69]:
e = np.array([[1,2,3], [4,5,6]])
print(e, e.ndim, e.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [70]:
np.concatenate((d,e))

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [71]:
f = np.array([[1,2],[3,4],[5,6]])
print(f, f.ndim, f.shape)

[[1 2]
 [3 4]
 [5 6]] 2 (3, 2)


In [82]:
# e는 2행 3열, f는 3행 2열으므로 맞지 않아 합쳐지지 않음(오류 발생)
# np.concatenate((e,f), axis=1)

In [77]:
# 전치행렬 : 행과 열을 바꿈
print(f)
print(f.shape)
print()
print(f.T)
print(f.T.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 3 5]
 [2 4 6]]
(2, 3)


# 전치 행렬 만들기 
- .T
- .transpose()

In [84]:
# f를 전치행렬로 변환하면 2행 3열로 변환되어 합치는 것 가능
np.concatenate((e,f.T), axis=1)

array([[1, 2, 3, 1, 3, 5],
       [4, 5, 6, 2, 4, 6]])

In [88]:
print(e.T)
print()
print(e.transpose())

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


# 브로드 캐스팅
- 벡터와 스칼라, 혹은 매트릭스와 벡터를 연산할 때 자동으로 행렬 크기를 맞춰주는 것


In [96]:
a = np.arange(1,16).reshape(3,5)
print(a, a.ndim, a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 2 (3, 5)


In [93]:
# 동일한 행과 열의 데열에 각각 10이 들어가 있음
# 해당 행과 열에 맞는 데이터끼리 더해서 표현
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [95]:
b = np.array([10, 20, 30, 40, 50])
print(b, b.ndim, b.shape)

[10 20 30 40 50] 1 (5,)


In [98]:
# 1행 5열짜리 b 배열이 3번 반복하여 a의 각 행의 데이터와 더해짐
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])