# 데이터 분석
- 인공지능(AI)
    - 머신러닝(ML)
    - 딥러닝(DL)

----------
- 머신러닝_데이터 분석
    - 지도학습 : 데이터에 정답이 포함된 경우
        - 분류분석, 회귀분석 등
    - 비지도학습 : 데이터에 정답이 없는 경우
        - 군집분석
-------
- 딥러닝_데이터 분석
    - 자연어 분석(NLP)
        - 언어 분석 -> 금융권 신용평가, 연체여부 확인, 금융사기 등 
        - 긍정적 / 부정적 여부 확인
    - 이미지 분석
        - 얼굴인증(얼굴 이미지 = 서버의 얼굴 이미지와 동일 여부 확인), 생체인증
        - 퀀트 투자 : 주가와 같은 시계열 데이터의 흐름을 이미지로 인식하여 패턴 파악 및 자동화

# Numpy
- https://numpy.org/numpy-tutorials/
- numpy : Nemerical Python 과학적, 산업적 연상을 위한 패키지
- 다차원 배열, 행렬 연산에 주로 사용
- numpy는 python의 .list와 비슷한 자료형
- 순서가 있는 자료형
- 파이썬의 list와의 차이는 자료형이 1가지만 들어간다


## 차원
- 0차원 = 점, 스칼라(a = 10)
- 1차원 = 선 ----- 벡터, 배열, list, tuple
    - 벡터는 방향을 가진 데이터
    - [1,2,3,4]
- 2차원 = 면, 가로/세로, DB 테이블, DataFrame, matrix
- 3차원 = 입체, 가로(x)/세로(y)/깊이(z), 정육면체
- 4차원 = 3차원 요소가 2개 이상
- 5차원 = 4차원 요소가 2개 이상

------------

- Excel : 기본적으로 2차원(가로/세로)
    - 하나의 셀 = 스칼라
    - 행 벡터(가로), 열 벡터(세로)

In [2]:
import numpy as np

In [9]:
# 1차원 데이터
a = np.array([1,2,3,4,5])

In [10]:
# 스칼라
s = 10

- 차원을 출력하는 메서드 : .ndim
- 차원의 형태를 출력하는 메서드 : .shape

In [11]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [38]:
# 방향이 없는 벡터
a.shape

(5,)

In [42]:
# 새로 방향을 가진 1차원 데이터
a2 = np.array([[1],[2],[3],[4],[5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [48]:
print(a2.ndim)
print(a2.shape)

2
(5, 1)


In [47]:
# 열벡터
a3 = np.array([[1,2,3,4,5]])
a3.shape

(1, 5)

In [37]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [18]:
print(c.ndim)
print(c.shape) # (행, 열) : 2개(2차원)

2
(2, 5)


In [49]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]],
             [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])

In [50]:
print(d.ndim)
print(d.shape) # ((행/열)2차원 데이터의 수, 행, 열) : 3개(3차원)

3
(4, 2, 5)


In [35]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])

In [29]:
print(e.ndim)
print(e.shape) # (3차원 데이터의 수,(행/열)2차원 데이터의 수, 행, 열) : 4개(4차원)

4
(2, 2, 2, 5)


In [34]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]],
             [[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]],
             [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])

In [51]:
print(f.ndim)
print(f.shape) # (4차원 데이터의 수, 3차원 데이터의 수,(행/열)2차원 데이터의 수, 행, 열) : 5개(5차원)

5
(2, 2, 2, 2, 5)


In [59]:
f[0][0][0][0]

array([1, 2, 3, 4, 5])

# Numpy 사용 이유
- 행렬 연산이 쉽고 빠르기 때문

In [65]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)
print(scalar + 10)

15
25


In [67]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]

# 리스트의 요소에 10을 곱한 후 다시 리스트로 만드세요

result = []
for num in b1:
    result.append(num*10)
print(result)

[10, 20, 30, 40, 50]


In [69]:
result2 = [num*10 for num in b1]
result2

[10, 20, 30, 40, 50]

In [77]:
# 2차원 데이터 계산 *10
second = np.array([[1,2,3], [1,2,3]])
print(second, second.ndim, second.shape)

[[1 2 3]
 [1 2 3]] 2 (2, 3)


In [102]:
result = []
for num in second:
#     print(num)
    mid_result = []
    for number in num:
        mid_result.append(number * 10)
    result.append(mid_result)
print(result)


[[np.int64(10), np.int64(20), np.int64(30)], [np.int64(10), np.int64(20), np.int64(30)]]


In [103]:
result = np.array(result)
print(result.ndim)
print(result.shape)

2
(2, 3)


In [80]:
# 3차원 데이터의 요소에 10 곱셈
third = np.array([[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]])
print(third, third.ndim, third.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 3 (2, 2, 3)


In [104]:
result = []

for num1 in third:
#     print(num1)
    num1_result = []
    for num2 in num1:
#         print(num2)
        num2_result = []
        for num3 in num2:
            num2_result.append(num3 * 10)
        num1_result.append(num2_result)
    result.append(num1_result)
print(result)


[[[np.int64(10), np.int64(20), np.int64(30)], [np.int64(10), np.int64(20), np.int64(30)]], [[np.int64(10), np.int64(20), np.int64(30)], [np.int64(10), np.int64(20), np.int64(30)]]]


In [105]:
result = np.array(result)
print(result.ndim)
print(result.shape)

3
(2, 2, 3)


In [111]:
# 4차원 데이터 요소에 10 곱셈
forth = np.array([[[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]],
                 [[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]]])
print(forth.ndim, forth.shape)

4 (2, 2, 2, 3)


In [108]:
forth * 10

array([[[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]],


       [[[10, 20, 30],
         [10, 20, 30]],

        [[10, 20, 30],
         [10, 20, 30]]]])

In [110]:
# 5차원 데이터 요소에 10 곱셈
fifth = np.array([[[[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]],
                 [[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]]],
                 [[[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]],
                 [[[1,2,3],[1,2,3]],[[1,2,3], [1,2,3]]]]])
print(fifth.ndim, fifth.shape)

5 (2, 2, 2, 2, 3)


In [113]:
fifth * 10

array([[[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]],



       [[[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]],


        [[[10, 20, 30],
          [10, 20, 30]],

         [[10, 20, 30],
          [10, 20, 30]]]]])

# Numpy에서 자주 사용하는 메서드
- .ndim : 몇 차원인지 확인
- .shape : 몇 차원, 몇행, 몇열로 되어 있는지 구조 확인
- .size : 배열 안에 있는 요소의 총 개수가 몇 개인지 확인
- .dtype : 데이터 타입이 무엇인지 확인

In [114]:
print(fifth.ndim)
print(fifth.shape)
print(fifth.size)
print(fifth.dtype)

5
(2, 2, 2, 2, 3)
48
int64


In [119]:
# fifth / 2


# ndarray 생성
- numpy의 기본 자료형 ndarray
- np.array(리스트/튜플)
- 자료형은 반드시 1가지만 넣기


In [121]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [122]:
print(*[1,2,3,4,5])

1 2 3 4 5


In [123]:
e = np.array((1,2,3,4,5))
e

array([1, 2, 3, 4, 5])

In [131]:
e = np.array((1,2,3.14,4,5))
e.dtype

dtype('float64')

In [127]:
e3 = np.array((True, 1,2,3.14, '4',5))
print(e3)
e3.dtype

['True' '1' '2' '3.14' '4' '5']


dtype('<U32')

- np.arange(시작, 끝, step)


In [134]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [135]:
a3 = np.arange(1,101)
a3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [137]:
# .reshape(행, 열) : 벡터를 원하는 크기의 matrix 또는 다차원 배열로 변환
print(a3.ndim)
print(a3.shape)

a4 = a3.reshape(20,5)
print(a4.ndim)
print(a4.shape)

1
(100,)
2
(20, 5)


In [141]:
a5 = a3.reshape(5,4,5)
print(a5.ndim)
print(a5.shape)

3
(5, 4, 5)


In [144]:
a6 = a3.reshape(4, 25)
print(a6.ndim)
print(a6.shape)
a6

2
(4, 25)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [145]:
# flatten() : 다차원 배열을 1차원으로 펼쳐줌
a7 = np.arange(24)
a7 = a7.reshape(3,2,2,2)
a7

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [150]:
a72 = a7.flatten()
print(a72.ndim)
print(a72.shape)

1
(24,)


In [153]:
# np.flip() : 행렬의 순서 뒤집는 경우
a73 = a72.reshape(3,2,2,2)
np.flip(a73)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [155]:
a73[-1]

array([[[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [160]:
# np.linspace(시작, 끝, 구간 수) : 정해진 숫자 범위 안에서 균등한 구간을 나누는 경우
np.linspace(1,10, 539)

array([ 1.        ,  1.01672862,  1.03345725,  1.05018587,  1.0669145 ,
        1.08364312,  1.10037175,  1.11710037,  1.133829  ,  1.15055762,
        1.16728625,  1.18401487,  1.20074349,  1.21747212,  1.23420074,
        1.25092937,  1.26765799,  1.28438662,  1.30111524,  1.31784387,
        1.33457249,  1.35130112,  1.36802974,  1.38475836,  1.40148699,
        1.41821561,  1.43494424,  1.45167286,  1.46840149,  1.48513011,
        1.50185874,  1.51858736,  1.53531599,  1.55204461,  1.56877323,
        1.58550186,  1.60223048,  1.61895911,  1.63568773,  1.65241636,
        1.66914498,  1.68587361,  1.70260223,  1.71933086,  1.73605948,
        1.7527881 ,  1.76951673,  1.78624535,  1.80297398,  1.8197026 ,
        1.83643123,  1.85315985,  1.86988848,  1.8866171 ,  1.90334572,
        1.92007435,  1.93680297,  1.9535316 ,  1.97026022,  1.98698885,
        2.00371747,  2.0204461 ,  2.03717472,  2.05390335,  2.07063197,
        2.08736059,  2.10408922,  2.12081784,  2.13754647,  2.15

In [163]:
np.linspace(0,1, 13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

In [164]:
# 정렬, .sort(), sorted()
f =np.array([5,7,11,1,3,2,54,0,0.5,68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

In [167]:
f.sort() # 저장하지 않아도 자동으로 저장되메
f

array([ 0. ,  0.5,  1. ,  2. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [169]:
# 저장하고 싶지 않다면 sorted 활용
sorted(f)

[np.float64(0.0),
 np.float64(0.5),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(7.0),
 np.float64(11.0),
 np.float64(54.0),
 np.float64(68.0)]

In [171]:
sorted(f, reverse=True)

[np.float64(68.0),
 np.float64(54.0),
 np.float64(11.0),
 np.float64(7.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(0.5),
 np.float64(0.0)]

In [178]:
f = f.reshape(2,5)
f.sort()
f

array([[ 0. ,  0.5,  1. ,  2. ,  3. ],
       [ 5. ,  7. , 11. , 54. , 68. ]])

In [179]:
# argsort() : 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
g = np.array([5,0.5, -7, 42,10,0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [181]:
# 2,5,1,0,4,3
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])

In [184]:
g[s][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])